# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home Bar Tips
email: webmaster@homebartips.com
description: >
  A podcast about the craft of drinks in your kitchen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://homebartips.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage
name: "Addison Berry"

# Google Analytics
analytics_id: "UA-98667695-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate

collections:
  ingredient:
    output: true
    permalink: /ingredients/:path/
  drink:
    output: true
    permalink: /drinks/:path/

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: page
  -
    scope:
      path: ""
      type: drink
    values:
      layout: page
  -
    scope:
      path: ""
      type: ingredient
    values:
      layout: page

sass:
    style: compressed 
